-- MySQL Script generated by MySQL Workbench
-- Tue May 16 15:17:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateYear` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `typePerson` VARCHAR(45) NULL,
  `speciality` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `Person_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Subject_Person1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_Subject_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `academia`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Subject_id` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Team_Subject1_idx` (`Subject_id` ASC),
  CONSTRAINT `fk_Team_Subject1`
    FOREIGN KEY (`Subject_id`)
    REFERENCES `academia`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateA` VARCHAR(45) NULL,
  `hStart` VARCHAR(45) NULL,
  `hEnd` VARCHAR(45) NULL,
  `remark` TEXT NULL,
  `DeliveredTools` VARCHAR(45) NULL,
  `Team_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Appointment_Team1_idx` (`Team_id` ASC),
  CONSTRAINT `fk_Appointment_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `academia`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Feature` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `state` TINYINT NULL,
  `typePerson` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `Subject_id` INT NULL,
  `Team_id` INT NULL,
  `Appointment_id` INT NULL,
  `acceptFeature` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Feature_Subject1_idx` (`Subject_id` ASC),
  INDEX `fk_Feature_Team1_idx` (`Team_id` ASC),
  INDEX `fk_Feature_Appointment1_idx` (`Appointment_id` ASC),
  CONSTRAINT `fk_Feature_Subject1`
    FOREIGN KEY (`Subject_id`)
    REFERENCES `academia`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feature_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `academia`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feature_Appointment1`
    FOREIGN KEY (`Appointment_id`)
    REFERENCES `academia`.`Appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`DepositBox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`DepositBox` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `limitDate` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Document` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `depoDate` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `Team_id` INT NULL,
  `DepositBox_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Document_Team1_idx` (`Team_id` ASC),
  INDEX `fk_Document_DepositBox1_idx` (`DepositBox_id` ASC),
  CONSTRAINT `fk_Document_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `academia`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_DepositBox1`
    FOREIGN KEY (`DepositBox_id`)
    REFERENCES `academia`.`DepositBox` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`wallMessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`wallMessage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `Person_id` INT NULL,
  `dateMessage` VARCHAR(45) NULL,
  `hourMessage` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wallMessage_Person1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_wallMessage_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `academia`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`wallCom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`wallCom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `wallMessage_id` INT NULL,
  `Person_id` INT NULL,
  `dateMessage` VARCHAR(45) NULL,
  `hourMessage` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wallCom_wallMessage1_idx` (`wallMessage_id` ASC),
  INDEX `fk_wallCom_Person1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_wallCom_wallMessage1`
    FOREIGN KEY (`wallMessage_id`)
    REFERENCES `academia`.`wallMessage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wallCom_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `academia`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`Person_has_Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`Person_has_Team` (
  `Person_id` INT NULL,
  `Team_id` INT NULL,
  INDEX `fk_Person_has_Team_Team1_idx` (`Team_id` ASC),
  INDEX `fk_Person_has_Team_Person1_idx` (`Person_id` ASC),
  CONSTRAINT `fk_Person_has_Team_Person1`
    FOREIGN KEY (`Person_id`)
    REFERENCES `academia`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_has_Team_Team1`
    FOREIGN KEY (`Team_id`)
    REFERENCES `academia`.`Team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
